
all: lab4.o metodFromLr4.o
	gcc lab4.o metodFromLr4.o

lab4.o: lab4.c metodFromLr4.h structComposition.h
	gcc -c lab4.c

metodFromLr4.o: metodFromLr4.c metodFromLr4.h structComposition.h
	gcc -c metodFromLr4.c